[package]
name = "testruct-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
testruct-core = { path = "../core" }
testruct-ui = { path = "../ui", optional = true }
anyhow = { workspace = true }
clap = { version = "4.5", features = ["derive"] }

[features]
ui = ["testruct-ui"]
